# -*- coding: utf-8 -*-
"""funciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nnz1Zh8pppoy8_WPqp950q14OlXhy2Y5
"""

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer ### para imputación
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import cross_val_predict, cross_val_score, cross_validate
import joblib
from sklearn.preprocessing import StandardScaler ## escalar variables

###########Esta función permite ejecutar un archivo  con extensión .sql que contenga varias consultas
def ejecutar_sql (nombre_archivo, cur):
  sql_file=open(nombre_archivo)
  sql_as_string=sql_file.read()
  sql_file.close
  cur.executescript(sql_as_string)

#Función para imputar las variables categoricas
def imputar_fc(df, list_cat):
  df_c = df[list_cat]

  imputer_c = SimpleImputer(strategy='most_frequent')
  imputer_c.fit(df_c)
  X_c = imputer_c.transform(df_c)
  df_c = pd.DataFrame(X_c, columns=df_c.columns)

  df[list_cat] = df_c  # Actualizar las columnas imputadas en el DataFrame original
  return df

